### ISSUE TITLE
Error while installing pip on Ubuntu

### ISSUE THREAD

**Issue by tarunamahajan** [moezali1/MMA865#1]
Hi Moez, Rishi

I have been getting the below errors while installing pip on Ubuntu terminal. 
Attaching the image of the error as well. 

Error - 
![image](https://user-images.githubusercontent.com/73365210/130877116-afeec748-683f-420a-9eb3-d63764d5824c.png)

**Comment by Rjotsin** [comment]
@tarunamahajan any update? looking to close this

**Comment by tarunamahajan** [comment]
@Rjotsin yea, it turns out the issue was with the firewall on my office laptop. I was able to resolve this by switching to my personal laptop. thanks

**Comment by Rjotsin** [comment]
Thanks, please close the issue @tarunamahajan
