### ISSUE TITLE
Errors when run Automl.py from office hour

### ISSUE THREAD

**Issue by Lucy-wo** [moezali1/MMA865#11]
Hi,

I am trying to run the office hour provided streamlit code called **automl.py**, I got this error, could you please help me look into it? 

**My code:**

```
import streamlit as st
import pandas as pd
from PIL import Image
from pycaret.regression import setup, compare_models, plot_model, pull, get_config, plot_model

image = Image.open('queens_image.jpg')

def automl():
    st.header("Smith AutoML")
    st.image(image)

    file_input = st.file_uploader('File uploader', type=['csv'])
    
    if file_input is not None:
        data = pd.read_csv(file_input)
        st.dataframe(data)

        st.header("Exploratory Data Analysis")
        data_describe = data.describe()
        st.dataframe(data_describe)

        st.header("Please Select Your Target")
        target_name = st.selectbox("Target", data.columns)
        submit_button = st.button("Initialize Setup")

        if submit_button:
            s = setup(data, target = target_name, silent = True)
            setup_results = pull()
            st.dataframe(setup_results.data)

            st.header("Transformed Train Set")
            transformed_train = get_config('X_train')
            st.dataframe(transformed_train)

            st.header("Model Training")

            with st.spinner(text='Multiple Models are Training. Please grab your coffee!!!'):
                best_model = compare_models()
                results = pull()
                st.dataframe(results)

            st.header("Model Analysis")
            plot_model(best_model, plot = 'residuals', display_format='streamlit')
            plot_model(best_model, plot = 'error', display_format='streamlit')
            plot_model(best_model, plot = 'cooks', display_format='streamlit')


if __name__ == "__main__":
    automl()
```

**My error:**
![Screen Shot 2021-09-07 at 7 06 51 PM](https://user-images.githubusercontent.com/59848049/132421378-fc6af994-02b9-4a6b-bd27-f74a92a07485.png)

**Comment by Rjotsin** [comment]
hmmm same error for me, I can fix this in the file but I want to make sure I'm not missing something before hand. This is Streamlit2 to my understanding with diamond_short. @moezali1 and idea why this is happening? I'm assuming it worked prior

**Comment by moezali1** [comment]
@Rjotsin @Lucy-wo It seems like the `Price` column is treated as an object when the file is loaded. Lucy, can you try uploading a different dataset and see if you can reproduce this error?

**Comment by Lucy-wo** [comment]
@moezali1 I tried several different dataset, it still have same issue. And I saw the

**Comment by Lucy-wo** [comment]
Hi @moezali1  and @Rjotsin , I tried a different dataset, had the same issue. Please see the picture below, and I also attached the dataset I was using. From the data exploration part, you can see that it shows the 'solar system output' is float, not a string. Please advise me, or I could ask during office hours. Thank you.

![Screen Shot 2021-09-12 at 8 00 18 PM](https://user-images.githubusercontent.com/59848049/133007024-4913e88d-76b8-48e6-8791-dc981f2b3299.png)
[02 CSV data -- Solar Output and Power Consumption - 2mo.csv](https://github.com/moezali1/MMA865/files/7150522/02.CSV.data.--.Solar.Output.and.Power.Consumption.-.2mo.csv)
