### ISSUE TITLE
1. Tokenization notebook issue 

### ISSUE THREAD

**Issue by TracyTrinh** [moezali1/MMA865#12]
I have run the 1. Tokenization notebook but get errors as below

# sentence tokenize function
sentence = nltk.sent_tokenize(text)

LookupError: 
**********************************************************************
  Resource [93mpunkt[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt/english.pickle[0m

  Searched in:
    - 'C:\\Users\\trang/nltk_data'
    - 'C:\\Software\\Anaconda3\\envs\\mma\\nltk_data'
    - 'C:\\Software\\Anaconda3\\envs\\mma\\share\\nltk_data'
    - 'C:\\Software\\Anaconda3\\envs\\mma\\lib\\nltk_data'
    - 'C:\\Users\\trang\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'

**Comment by Rjotsin** [comment]
I think it says in the code how to fix it, try running the following:
```
import nltk
nltk.download('punkt')
```

**Comment by moezali1** [comment]
Hi @TracyTrinh 

Can you please confirm if the said issue has been resolved? If yes, can you please close this ticket?

Thanks

**Comment by TracyTrinh** [comment]
yes, sure! Thank you, Rishi and Moez
