### ISSUE TITLE
HDP Sandbox installing issue

### ISSUE THREAD

**Issue by Williamzhong21** [moezali1/MMA865#2]
![image](https://user-images.githubusercontent.com/89561992/130892155-27013d89-2eb8-45d3-b484-400ecd28f7d0.png)

I had issue when I tried to install HDP sand box, screen shot is attached.

**Comment by Rjotsin** [comment]
@Williamzhong21 any update? looking to close this

**Comment by Williamzhong21** [comment]
Hi Rishi,

Thanks for following up! My laptop died, just installed on another laptop, installation passed.

Best regards,
William

Sent from my iPhone

On Aug 30, 2021, at 1:37 AM, Rishi Jotsinghani ***@***.***> wrote:

﻿

@Williamzhong21<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWilliamzhong21&data=04%7C01%7Cwilliam.zhong%40queensu.ca%7C00e16fe86d3b46501f4608d96b6fce51%7Cd61ecb3b38b142d582c4efb2838b925c%7C1%7C0%7C637658950211795562%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=h4gv%2BOqjDkJSyEUghy%2FZTA5FQIyQbPEgvZ5vZKi6qaw%3D&reserved=0> any update? looking to close this

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmoezali1%2FMMA865%2Fissues%2F2%23issuecomment-908021651&data=04%7C01%7Cwilliam.zhong%40queensu.ca%7C00e16fe86d3b46501f4608d96b6fce51%7Cd61ecb3b38b142d582c4efb2838b925c%7C1%7C0%7C637658950211795562%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=urjIwrBVqC1yZJPDGJu9cj7F1KFQaLsRaI3qzsidLf4%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVLJXCEIMKSHFHOZIOD4D33T7MDGXANCNFSM5C2L7BTA&data=04%7C01%7Cwilliam.zhong%40queensu.ca%7C00e16fe86d3b46501f4608d96b6fce51%7Cd61ecb3b38b142d582c4efb2838b925c%7C1%7C0%7C637658950211805560%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1N8Wkl49o5CRqylH63kdsMQqMq6XZv6i91NamLvkJWk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cwilliam.zhong%40queensu.ca%7C00e16fe86d3b46501f4608d96b6fce51%7Cd61ecb3b38b142d582c4efb2838b925c%7C1%7C0%7C637658950211805560%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BEvEdncEhlTh%2B7qNgJHzMdfmK5jwFGflLsWkCdBueR8%3D&reserved=0> or Android<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cwilliam.zhong%40queensu.ca%7C00e16fe86d3b46501f4608d96b6fce51%7Cd61ecb3b38b142d582c4efb2838b925c%7C1%7C0%7C637658950211815551%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XM6%2BbBSfftDsRngtyZNNCiDpq2V7Ej6p4bnQeoPrhTE%3D&reserved=0>.

**Comment by Rjotsin** [comment]
@Williamzhong21 great, please close the ticket
