### ISSUE TITLE
Error when calling Spark NLP - TypeError: ‘JavaPackage’ object is not callable

### ISSUE THREAD

**Issue by jkuntze** [moezali1/MMA865#3]
TypeError: ‘JavaPackage’ object is not callable when calling Tokenizer() in the Azure Databricks environment, after installing sparknlp (which was not available to start with). 
Team Ossington cluster in Azure Databricks.

# Import Spark NLP
from sparknlp.base import *
from sparknlp.annotator import *
from sparknlp.pretrained import PretrainedPipeline
import sparknlp
from pyspark.sql import SparkSession
from pyspark.ml import Pipeline

# Start Spark Session with Spark NLP
spark = sparknlp.start()

# NLP Pipeline using Spark NLP
from pyspark.ml.feature import HashingTF, IDF, StringIndexer, SQLTransformer,IndexToString
from pyspark.ml.classification import LogisticRegression
from pyspark.ml.evaluation import MulticlassClassificationEvaluator# convert text column to spark nlp document

document_assembler = DocumentAssembler() \
    .setInputCol("text") \
    .setOutputCol("document")# convert document to array of tokens
tokenizer = Tokenizer() \
  .setInputCols(["document"]) \
  .setOutputCol("token")

**Comment by Rjotsin** [comment]
I found the issue to note:
Library was not installed with full instructions, can be found here: https://nlp.johnsnowlabs.com/docs/en/install

Should be fixed on all clusters now
