### ISSUE TITLE
Pipeline - Feature Engineering - Sequence? 

### ISSUE THREAD

**Issue by joyceliu1101** [moezali1/MMA865#4]
Hi Moez, 

I want to do feature engineering on specific categorical variables and also do the imputation on missing values, so I defined the features and the methods. It showed an error of " Input contains NaN" when running the fit_transform on train data.  Is it because "ColumnTransformer" method would execute the code in parallel?  We should set up the sequence of the steps in the pipeline, eg. do the imputation first and then do the feature engineering, is my understanding correct, pls advise. 

[Error_pipeline_sequence.zip](https://github.com/moezali1/MMA865/files/7085933/Error_pipeline_sequence.zip)

Thanks, 
Joyce Liu

**Comment by Rjotsin** [comment]
Hi,

so looks like the ColumnTransformer isn't respecting your order, this is probably due to ColumnTransformer trying to apply multiple transformations on the same column. The OneHotEncoder is applying before the Imputation.

Your best bet is to either do the imputation first, followed by everything else OR make them in the same pipeline. Something like this:

```
ohe_feature = ['department']
ohe_pipeline =Pipeline(steps = [('impute', SimpleImputer(strategy='most_frequent')) , ('ohe',OneHotEncoder(handle_unknown='ignore', sparse=False))])

te_feature = ['salary']
te_pipeline =Pipeline(steps = [('impute', SimpleImputer(strategy='most_frequent')), ('te', TargetEncoder(handle_unknown='ignore'))])

from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer(transformers=[
                               ('numeric', numeric_pipeline, numeric_features)
                               ,('te_features', te_pipeline,te_feature)
                               ,('ohe_features', ohe_pipeline,ohe_feature)
], remainder='passthrough')

# fit entire data pipeline
preprocessor.fit_transform(X_train.sort_index(), y_train.sort_index())
```

**Comment by moezali1** [comment]
@joyceliu1101 Does this solve your problem?

**Comment by joyceliu1101** [comment]
Thanks, Rjotsin / Moez ! It solved.  I got it:  we can set up the sequence to run the code in the pipeline (steps), but there is no order in ColumnTransformer. Thanks again!

**Comment by Rjotsin** [comment]
Thanks @joyceliu1101 please close the ticket
