### ISSUE TITLE
Issue to run the code of '1. Dask Distributed Training'

### ISSUE THREAD

**Issue by Lucy-wo** [moezali1/MMA865#6]
Hi Moez and Rishi,

I tried to run the code of **1. Dask Distributed Training** which is provided by Day2 material. BTW, I am using the Mac Book. Here is what I got; I am not sure if anything went wrong. Could you please advise me? (I did not change any code)

**Code:**
`t1 = time()
inc.fit(X_train, y_train, classes=classes)
t2 = time()
delt = round(t2-t1,3)
print(f"Fitting time:{delt} seconds")
t1 = time()
score=inc.score(X_test, y_test)
t2 = time()
delt = round(t2-t1,3)
print(f"Score evaluation time:{delt} seconds")
print(f"Accuracy score on the test set: {score}")`

**Result:**
![Screen Shot 2021-09-03 at 11 31 15 PM](https://user-images.githubusercontent.com/59848049/132081040-ea1bf972-dad4-4b30-af03-dfdd393b3c3f.png)

Thank you,
SY

**Comment by Rjotsin** [comment]
Try changing the second cell in the notebook to this: 
```
client = Client(n_workers=4, threads_per_worker=2, 
                processes=False, 
                memory_limit='4 GB',
                silence_logs='error',interface='lo0')
client
```

Referenced here: https://github.com/dask/dask/issues/5085#issuecomment-513043034

**Comment by Lucy-wo** [comment]
Hi Rishi, I tried the code you provided, but give me the error: **RuntimeError: already listening on '127.0.0.1:0'**

<img width="1369" alt="Screen Shot 2021-09-06 at 11 03 54 AM" src="https://user-images.githubusercontent.com/59848049/132236399-b7a74921-4c97-4e9c-82b9-46377177581f.png">

Thank you,
SY

**Comment by Rjotsin** [comment]
Hi, did you end up solving this? I don't remember if we looked at this in the office hours

**Comment by Lucy-wo** [comment]
Hi Rishi, sorry not yet. I was not able to join last week's office hour, I will join this coming one and ask you.

**Comment by moezali1** [comment]
Hi @Lucy-wo 

Can you please confirm if the said issue has been resolved? If yes, can you please close this ticket?

Thanks

**Comment by Lucy-wo** [comment]
@moezali1 @Rjotsin , the issue not be solved yet, I will attend the following office hour. Thank you. :)
