### ISSUE TITLE
"OSError: Reason: image not found" when executing "from pycaret.classification import *" in Python

### ISSUE THREAD

**Issue by ijawadi** [moezali1/MMA865#8]
Environment: macOS BigSur 11.5.2
MacBook Pro (2015), Intel Core i7.
 
Error description:
when executing the following command, I get OS Error:

Command:
_from pycaret.classification import *_

Error Message:
_OSError: dlopen(/Users/ijawadi/opt/anaconda3/envs/mma/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/ijawadi/opt/anaconda3/envs/mma/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so
  Reason: image not found_

Actions:
I uninstalled/reinstalled Anaconda using the following sites:
https://towardsdatascience.com/manage-your-python-virtual-environment-with-conda-a0d2934d5195 
https://mattbanderson.com/so-you-hosed-your-mac-os-python-install/

but still, get the same error.  
Need assistance.  Thank you.
<img width="889" alt="Screen Shot 2021-09-04 at 7 04 11 PM" src="https://user-images.githubusercontent.com/26658283/132110011-2efd666f-b352-49c6-9b4e-b52d18d3b63c.png">
<img width="809" alt="Screen Shot 2021-09-04 at 7 04 43 PM" src="https://user-images.githubusercontent.com/26658283/132110019-825c4465-7012-4fb3-b756-d31760e36cd2.png">
<img width="796" alt="Screen Shot 2021-09-04 at 7 05 07 PM" src="https://user-images.githubusercontent.com/26658283/132110025-2c759853-c1a1-41ed-9b65-65c78f4c2c18.png">

**Comment by Rjotsin** [comment]
Looks like you don't have lightgbm installed, I referred a solution in this: https://github.com/moezali1/MMA865/issues/9#issuecomment-913225920

Please try everything in that comment

**Comment by ijawadi** [comment]
Hi @Rjotsin ,
thank you for your help and I tried all, but regretfully I still get the same error, mind you the error is now clearer:
<img width="805" alt="Screen Shot 2021-09-07 at 9 30 38 AM" src="https://user-images.githubusercontent.com/26658283/132353286-efca1e76-e7e7-46d3-9dfe-6a194c3bcebe.png">

**Comment by ijawadi** [comment]
@Rjotsin,
I restarted my Mac again and rerunning the commands.  here is a screenshot as I run instructions from the first site you provided: https://medium.com/tinghaochen/install-lightgbm-on-macos-high-sierra-1c640861e914 
<img width="568" alt="Screen Shot 2021-09-07 at 9 43 33 AM" src="https://user-images.githubusercontent.com/26658283/132355264-7a3cb181-20f5-42ec-bde6-beaa623d49fe.png">

**Comment by ijawadi** [comment]
@Rjotsin according to this, lightgbm already exists, but when trying to test, it can't find Facebook's prophet

**Comment by Rjotsin** [comment]
Can you close this ticket @ijawadi
