### ISSUE TITLE
Unable to download LightGMB on a mac

### ISSUE THREAD

**Issue by 20je12** [moezali1/MMA865#9]
Hello - I am having this error (attached below) when trying to run the code throughout the practicums in lecture - i believe this is due to the fact that I am running my program on a Mac, and LightGBM is not installed. 
Thanks. 
![Screen Shot 2021-09-05 at 11 24 16 AM](https://user-images.githubusercontent.com/90008646/132130431-1d05e551-e24e-409a-a246-c32dc02a90a4.png)

**Comment by Rjotsin** [comment]
Please try all three of these and let me know if the installation works:

https://medium.com/tinghaochen/install-lightgbm-on-macos-high-sierra-1c640861e914
https://github.com/microsoft/LightGBM/issues/1573#issuecomment-417679749
https://github.com/microsoft/LightGBM/issues/1369#issuecomment-396530298

The last one will need you to install lightgbm after the fact.

**Comment by 20je12** [comment]
I have followed the steps above and am getting an error (see below) when running the code in the first link 
<img width="773" alt="Screen Shot 2021-09-06 at 2 27 03 PM" src="https://user-images.githubusercontent.com/90008646/132249378-f4dd1b82-dc60-456c-95e3-21b362ae64d2.png">

**Comment by Rjotsin** [comment]
```git clone --recursive https://github.com/microsoft/LightGBM
cd LightGBM
export CXX=g++-8 CC=gcc-8 
mkdir build
cd build
cmake ..
make -j4```

**Comment by Rjotsin** [comment]
Can you close this ticket @20je12
